# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./webui.yaml
  - ./networkpolicy.yaml
  - ./home-agent-networkpolicy.yaml
  - ./control.yaml
  - ./nginx.yaml
  - ./mytops-api-catalog.configmap.json
  - ./mytops-workplace-api.configmap.json
  - ./idle-culler.yaml
  - ./mytops-idle-culler.configmap.json
  - ./mytops-home-agent.configmap.json
  - ./mytops-turn.yaml
  - ./coturn.yaml
  - ./mytops-webui.configmap.json
